#!/usr/bin/expect

proc scp {host password lfile rfile} {
	spawn scp $lfile root@$host:$rfile
	expect {
	  "assword:" { send -- "$password\r"
	  }
	  "you sure you want to continue connecting" {
	  send -- "yes\r"
	  expect "assword:"
	  send -- "$password\r"
	  }
	}
	expect $
}

set host [lrange $argv 0 0]
set lfile [lrange $argv 1 1]
set rfile [lrange $argv 2 2]
scp $host "password" $lfile $rfile


